//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpP2_Homework_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string PATRONYMIC { get; set; }
        public Nullable<int> DEPID { get; set; }
    }
}
